### ISSUE TITLE
Translatable theater names

### ISSUE THREAD

**Issue by FS-21** [secsome/FA2sp#1]
![imagen](https://user-images.githubusercontent.com/1371539/113312042-31d60e00-930a-11eb-84fa-1b8ab9293173.png)
Will be possible to unlink these strings for translations? 
Currently if you change the names of the Dropdown button with a Hex editor the map Theater will use that new string making the map unplayable.

For those with custom theaters it can be useful.

**Comment by secsome** [comment]
Well, I don't think it's quite necessary, but I will try to do that if it's really needed and when I'm available.

**Comment by secsome** [comment]
Implemented in the lastest develop.
