### ISSUE TITLE
Rules.ini and Art.ini for FA2

### ISSUE THREAD

**Issue by MikillRosen** [secsome/FA2sp#10]
Add a feature where FA2sp can use its own rules.ini and art.ini as an addition to the game's rules.ini and art.ini. TS map editors like Dawn of the Tiberium Age's map editor use this feature and so should RA2 YR map editors.

**Comment by secsome** [comment]
There is already a section in fadata.ini controlling the inifiles to read. see [Filenames].
e.g.
[Filenames]
Rules=rulesfs.ini
Art=artfs.ini
