### ISSUE TITLE
Trigger Painter

### ISSUE THREAD

**Issue by CatTanker** [secsome/FA2sp#11]
Currently, if you need to attach a trigger to multiple structures/vehicles/infantry you need to do it manually either through the map editor or through ini editing (if you have done it in a suitable order). Both of these methods are very time consuming.

My suggestion is to add a tool which allows you to paint triggers onto units (similar to the owner section)
it also allows for coops and challenges to be made easily, as hours of clicking and applying triggers are saved (especially on walls 😁

**Comment by secsome** [comment]
Being included in FA2sp 1.2.0 PropertyBrush feature
