### ISSUE TITLE
tunnel drawer optimizations 

### ISSUE THREAD

**Issue by McPwny** [secsome/FA2sp#13]
final alert 2 has a tunnel drawer feature that was meant to let mappers make and use the tunnel logic introduced in TS, the tunnels also being usable by mods with terrain expansions; however, the tunnel drawer feature has a slight malfunction in generating the code for the tunnels that renders the feature non-working. fixing the tunnel drawer would be a wonderful quality of life improvement.  

the error in the tunnel drawer's output is described in this ppmforum post in more detail
https://ppmforums.com/topic-42008/finalsun-tunnel-fixer/

**Comment by secsome** [comment]
Resolved in commit 0dfa59b0d6f0e1f3f968d723002e0795664cfd7a

**Comment by McPwny** [comment]
that was fast. good work
