### ISSUE TITLE
Crash with Heighten Ground + Morphables/Ramps

### ISSUE THREAD

**Issue by Starkku** [secsome/FA2sp#17]
Using the `Morphables` / `Ramps` feature for theater info, the editor sometimes crashes when raising ground & creating ramps. With default settings the crashes do not occur.

Crash dump etc: https://mega.nz/file/EzgiETRB#_cOVoPO0TkESkhM2eAI35KQagR8R-qmYa5rJfBmpYJA

**Comment by secsome** [comment]
I'm not sure if this can be stably reproduced.
