### ISSUE TITLE
option to save maps as .map

### ISSUE THREAD

**Issue by McPwny** [secsome/FA2sp#2]
most map makers these days write maps to be used over the cncnet client, which stupidly enough only reads .map extension maps. this leads to the weird workflow of saving a map as .yrm or .mpr, then opening the map in a text editor, then saving the map with a .map file extension. adding the option to save maps with a .map file extension from the editor would save a lot of headache.

**Comment by secsome** [comment]
Implemented in #5

**Comment by McPwny** [comment]
terrific work
