### ISSUE TITLE
Update the rendering pass to show damage and rubble frames for buildings based on health

### ISSUE THREAD

**Issue by ATHSE** [secsome/FA2sp#24]
The damage frame is probably the easier of the two to implement, but the rubble frame displaying on zero health would really help when making a map. Westwood did include a number of rubble tiles in the URBAN tileset, but most of these were just placeholders and totally inappropriate to use in a real map. Using the real rubble also allows choosing among hundreds of buildings for one with suitable rubble for the occasion.

Rubble frames don't block unit movement, so they can be a very useful decoration that doesn't obstruct the AI or pathfinding. I could also see this update making it a lot easier to create destroyed/post-apocalyptic cities.

**Comment by secsome** [comment]
Resolved in lastest develop.
