### ISSUE TITLE
fa2 crashes when trying to use trigger action 71 and 72

### ISSUE THREAD

**Issue by McPwny** [secsome/FA2sp#26]
as stated in the title, fa2 simply crashes whenever the ambient light related trigger actions 71 or 72 are used. to recreate the crash, simply open a new map, make a new trigger, and switch the trigger action number to 71 or 72.

**Comment by secsome** [comment]
Can you attach the crash dump here? I'm supposing you are using the lastest release, but I cannot reproduce that.

**Comment by McPwny** [comment]
ah, patching it to the newest version fixed the problem. sorry for wasting your time
