### ISSUE TITLE
地编会补Name和Owner

### ISSUE THREAD

**Issue by prry123** [secsome/FA2sp#27]
用记事本在地图里写入单位ini然后地编打开他会自个补齐没写的Name和Owner然后出问题。
比如：
[HTNK]
Primary=120mm
变成
[HTNK]
Primary=120mm
Owner=
Name=

**Comment by secsome** [comment]
You have to provide exact reproduce steps.
At least I cannot reproduce the `Owner` issue now.
And `Name` doesnt matter in fact.

**Comment by MapleEve** [comment]
BrowserRedraw.GuessMode=0		;猜测科技类型所属阵营的方式，0（默认）使用先决条件，1使用Owner第一项

**Comment by secsome** [comment]
> BrowserRedraw.GuessMode=0 ;猜测科技类型所属阵营的方式，0（默认）使用先决条件，1使用Owner第一项

Don't think its related. I cannot reproduce the issue no matter the `GuessMode` is 0 or 1 .

**Comment by MapleEve** [comment]
> > BrowserRedraw.GuessMode=0 ;猜测科技类型所属阵营的方式，0（默认）使用先决条件，1使用Owner第一项
> 
> Don't think its related. I cannot reproduce the issue no matter the `GuessMode` is 0 or 1 .

It's actually weird for me too. I'm using caco's pack verison, the fa2.sp will not guess Owner by using the latest dll version.

So poren should give a detailed FA2 version / mod and full reproduce vid.

**Comment by prry123** [comment]
> You have to provide exact reproduce steps. At least I cannot reproduce the `Owner` issue now. And `Name` doesnt matter in fact.

还有小队和特遣，小队[TeamTypes]里面注册的，但是地图里没有的小队，他会自己创建一个项目写上
Name=
Script=
TaskForce=

特遣同理会写一个Name=，虽然name没啥所谓
