### ISSUE TITLE
地编显示矿量与实际游戏内不符

### ISSUE THREAD

**Issue by prry123** [secsome/FA2sp#28]
首先矿量应该是和一格矿周围8个格子有没有矿相关，因此应该是有9个等级，以原版的黄金矿为例
地编显示的9个等级的矿量为 25   50  100  125  175  200  225  275  300
游戏内实际9个等级的矿量为  0    25   75   100  150  175  200  250  275
每个等级相差25矿，游戏内周围8格都没有矿的一格杂矿实际矿车采了没钱
所以导致冰天中矿地编显示67000，实际游戏60600，相差128x25x2,（冰天中矿占128格）

**Comment by MapleEve** [comment]
Let's say: WWSB
实际上这里有一个小悖论，在我们调试游戏的时候发现超级薄的一层矿，大概是25的量，矿车采进去是没矿的。
甚至有些地图贴图上有一层薄矿但是矿车采不了那个矿。
当然还是希望最后修复掉这个问题。

**Comment by MapleEve** [comment]
https://github.com/secsome/FA2sp/pull/31

86 找到代码里面计算这块了，我看了一下逻辑确实是在这一层 +1 然后相乘 Value 的，看看书记接受不接受这样的修改。

**Comment by secsome** [comment]
Closed by #31
