### ISSUE TITLE
Incorrect position of waypoint number text

### ISSUE THREAD

**Issue by CnC-RaVaGe** [secsome/FA2sp#33]
I created a new waypoint graphic for a previous version of FA2SP, now the waypoint text has been moved off center for some reason. Please see attached image.
![image](https://user-images.githubusercontent.com/54605063/227572022-3d37f054-987a-4ce2-a113-a6e1ba403fc3.png)

**Comment by secsome** [comment]
You can fix it by editing the config, see `FADATA.INI>ExtConfigs>Waypoint.Text.ExtraOffset=X,Y`
