### ISSUE TITLE
Small Tile Placement UI Size

### ISSUE THREAD

**Issue by CnC-RaVaGe** [secsome/FA2sp#34]
There seems to be too little space given to the "Tile Placement" UI menu, which seems to cut some of the text.

See attached image.
![image](https://user-images.githubusercontent.com/54605063/227574179-3fa91916-df41-46b9-be42-bb66a0aadaae.png)

Correct UI spacing:
![image](https://user-images.githubusercontent.com/54605063/227574793-ac8e0a5d-b992-4aa9-9ffe-0b468e25bdd9.png)

**Comment by secsome** [comment]
Fixed in lastest develop branch
