### ISSUE TITLE
Lighting menu changes don't get reset between map loads

### ISSUE THREAD

**Issue by ATHSE** [secsome/FA2sp#36]
See linked image. Setting the lighting choice in the menu, in the example to the "Lightning Storm" option, and then loading a new map, will screw up all the lighting settings used by the menu in the new map. It does not alter the code in the map, as in refering to the Edit->Lighting all values are correct, but it means choosing "None" or "Normal" doesn't fix things, it seems to stay broken for the entire session.

https://i.imgur.com/6tMEBL9.jpg

**Comment by ATHSE** [comment]
Attaching same image...
![6tMEBL9](https://user-images.githubusercontent.com/96433329/230787465-d7d0b723-0b35-49ba-b2ad-2dacdc11d05f.jpg)

**Comment by secsome** [comment]
Fixed in lastest develop
