### ISSUE TITLE
Complaining about Buildings overlap with Invisible Lightposts when saving?

### ISSUE THREAD

**Issue by ATHSE** [secsome/FA2sp#37]
![lightpost-overlap](https://user-images.githubusercontent.com/96433329/230993486-d60b8fef-444c-407c-98e5-a8f8bb341be7.jpg)

This didn't used to happen?

**Comment by ATHSE** [comment]
Perhaps you can just cull the lights from the comparison by looking for
InvisibleInGame=yes under the art?

**Comment by secsome** [comment]
Currently, I'm not quite sure what will lead to the game crush when you have overlapped buildings. Therefore I guess I will add a configurable list indicating the program that those building will be ignored.

**Comment by ATHSE** [comment]
The game does crash under normal circumstances with overlaps, but never when it's with the lightposts. Weirdly the lightposts have the normal 1x1 foundation not even 0x0, which could have indicated another reason.

Also the InvisibleInGame can't be the decider, because the non-invisible lightposts can overlap without crashing when the other building is destroyed, though in my tests the non-invisible lightpost got destroyed at the same time during the collapsed.

**Comment by ATHSE** [comment]
I wonder if it's actually GALITE the shared art for all the lightposts that's exempted?

**Comment by secsome** [comment]
Just introduced a tag to control the behaviour, close this issue for now.
