### ISSUE TITLE
expanded LAT functionality

### ISSUE THREAD

**Issue by McPwny** [secsome/FA2sp#6]
one major limitations to terrain expansions are that FA2/RA2 are hardcoded to support only 4 LAT (lookup adjacent tile) sets. in temperate they are "rough grass, dark grass, sand, pavement". for any additional sets added, the map makers are forced to place each edge of every tile by hand. expanding LAT functionality to support more than 4 hardcoded LAT types, if possible, would enable more diverse terrain detailing.

**Comment by secsome** [comment]
The LAT tiles will be recalculated in the game, so it's not quite useful for you to have LAT system implemented in FA2

**Comment by McPwny** [comment]
the core problem is that the LATS arent calculated in RA2 nor FA2 if they arent one of the hardcoded LAT types under [General] in the theater specific ini files. having both RA2 and FA2 recalculate them would be ideal, but if only FA2 calculates them it still should work as long as the edges are properly generated.

**Comment by CC-RaVaGe** [comment]
The game wouldn't recalculate them.
Adding auto LAT to be configurable on FA2 side would allow non-manual tile setting / randomisation.
