### ISSUE TITLE
expanded slope functionality

### ISSUE THREAD

**Issue by McPwny** [secsome/FA2sp#7]
another major obstacle for terrain makers and mappers is that there is no way to indicate to FA2 that a terrain set is a slope set, resulting in map makers having to place every angle of every slope by hand. expanding slope logic so that it can be applied to terrain sets (in the corresponding theater's ini, ideally) would help diversify maps a great deal

worth noting is that the newurban theater already does this. it seems that newurban has been hardcoded to apply slope logic to both the grass and urban pavement terrain types.

**Comment by secsome** [comment]
Resolved in the lastest develop

**Comment by McPwny** [comment]
terrific work
